import { ObjectSchema } from 'realm';
export const FormSchema: ObjectSchema = {
  name: 'FormSchema',
  primaryKey: '_id',
  properties: {
    _id: {
      type: 'int',
      indexed: true,
    },
    uid: 'string',
    name: 'string',
    age_group: 'string',
    gender: 'string',
    reason_not_cpf: 'string',
    cpf: 'string',
    email: 'string',
    city: 'string',
    street: 'string',
    district: 'string',
    number: 'string',
    region: 'string',
    zone: 'string',
    uf: 'string',
    zipcode: 'string',
    latitude: 'string',
    longitude: 'string',
    schollLevel: 'string',
    religion: 'string',
    comorbidity: 'bool',
    diabetes: 'bool',
    heartProblem: 'bool',
    kidneyDisease: 'bool',
    thyroid: 'bool',
    obesity: 'bool',
    otherComorbidity: 'string',
    affectedCovid19: 'bool',
    diagnosticConfirmation: 'bool',
    timeInterval: 'string',
    diagnosticMethod: 'string',
    treatmentPlace: 'string',
    hospitalTreatment: 'string',
    covidSequelae: 'string',
    status: 'string', // 'success' || 'pending' || 'error'
    created_at: 'date',
    updated_at: 'date',
  },
};
